### Exercise 1

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.   
Expected Output:

![](files/2022-11-14-20-51-15.png)

In [ ]:
import numpy as np

In [ ]:
# Up to you!



### Exercise 2

Write a NumPy program to create a new array of 3*5, filled with 2.   

Expected Output:

![](files\2022-11-22-16-57-03.png)


In [ ]:
# Up to you!



### Exercise 3

Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.  
Expected output:
[[ 0. 1. 2. 3. 4.]
..........
[ 0. 1. 2. 3. 4.]]

In [ ]:
# Up to you!



### Exercise 4
Write a NumPy program to reverse an array (first element becomes last).  

* Original array:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]  
* Reverse array:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [ ]:
# Up to you!



### Exercise 5
Write a NumPy program to create a 1D array containing 20 random integers between 1 and 6 (included).  
Next filter this array to a new one containing only the odd numbers.

In [ ]:
# Up to you!



### Exercise 6
Write a NumPy program to get the positions where elements of a and b match  

Input:  
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])  

Expected Output:  
#> (array([1, 3, 5, 7]),)

In [ ]:
# Up to you!



### Exercise 7
 Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.   
Checkerboard pattern:  
[[0 1 0 1 0 1 0 1]  
..........  
[0 1 0 1 0 1 0 1]  
[1 0 1 0 1 0 1 0]]  

In [ ]:
# Up to you!



### Exercise 8
 Write a NumPy program to create a 4x4 matrix.  
 Original array:

```
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]
[12 13 14 15]]  
```

* Extract all the elements of the first and fourth rows.  
Expected output:

```
[[ 0,  1,  2,  3], [12, 13, 14, 15]]
```

* Extract all the elements of the first and fourth columns.  
Expected output :

```
[[ 0 3]
[ 4 7]
[ 8 11]
[12 15]]
```

* Extract second and third elements of the second and third rows  
Expected output:

```
[[ 5 6]
[ 9 10]]
```

In [ ]:
# Up to you!



### Exercise 9
Import a dataset with numbers and texts _keeping the text intact_ in a python NumPy array.

The dataset can be found on this url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data  
Each row consists of 5 fields: 'sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'  
The first 4 fields are numbers, 'species' contains text.  

To load this dataset you need to use the genfromtxt() function and make sure that dtype is set to object. Otherwise the 'species' field will contain NaN values.  

Expected output (first 3 rows)
```
array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)
```

In [ ]:
# Up to you!



### Exercise 10
Import the iris dataset again but now just the first four columns.  
Check if there are any missing values in the sepallength (1st column).  
This can be done with the function isnan()  

Expected output:  
Number of missing values: 0  
Position of missing values:
```
(array([], dtype=int64),)
```

In [ ]:
# initialisation
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_numbers = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# iris_numbers[1,2] = np.nan
# iris_numbers[2,2] = np.nan
# # print(np.isnan(iris_numbers))
# print(np.where(np.isnan(iris_numbers)))

In [ ]:
# Up to you!



### Exercise 11
Compute the mean, median, standard deviation of iris's sepallength (1st column)  

Expected output:  
mean: 5.843333333333334   
median: 5.8   
standard deviation: 0.8253012917851409  

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

#iris contains objects --> must be converted to floats for calculations
sepallength = np.array(iris[:,0],dtype=float)

#alternative is load only first column and dtype it to float
# sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [ ]:
# Up to you!



### Exercise 12
Find the 5th and 95th percentile of iris's sepallength.  

Expected output: array([4.6  , 7.255])

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [ ]:
# Up to you!



### Exercise 13
Filter the rows in the iris data array that haves petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0  
The resulting array contains the 4 numeric fields for each retrieved row.  

Expected output: 
``` 
array([[4.8, 3.4, 1.6, 0.2],  
       [4.8, 3.4, 1.9, 0.2],  
       [4.7, 3.2, 1.6, 0.2],  
       [4.8, 3.1, 1.6, 0.2],  
       [4.9, 2.4, 3.3, 1. ],  
       [4.9, 2.5, 4.5, 1.7]])
```


In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_numbers = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
# Up to you!

